export { default as HeaderComponent } from './lib/HeaderComponent/HeaderComponent.vue'
export { default as FooterComponent } from './lib/FooterComponent/FooterComponent.vue'
export { default as MarketComponent } from './lib/MarketComponent/MarketComponent.vue'
export { default as BasketComponent } from './lib/BasketComponent/BasketComponent.vue'
export { default as OrdersComponent } from './lib/OrdersComponent/OrdersComponent.vue'
